version: "3"

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      ConnectionStrings__DefaultConnection: "Server=db;Port=3306;Database=TechChallenge;User=TechChallenge;Password=TechChallengeSoat4;"
    ports:
      - 8080:80
      - 8081:443
    networks:
      - techchallenge
    depends_on:
      - db

  db:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: TechChallenge
      MYSQL_USER: TechChallenge
      MYSQL_PASSWORD: TechChallengeSoat4
    ports:
      - 3306:3306
    networks:
      - techchallenge
    volumes:
      - techchallenge:/var/lib/mysql

networks:
  techchallenge:
    driver: bridge

volumes:
  techchallenge: